
services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - LOG_LEVEL=debug
    command: ["-debug"]
    networks:
      - glimpse-network

  agent:
    build:
      context: ..
      dockerfile: docker/Dockerfile.agent
    environment:
      - LOG_LEVEL=debug
      - SERVER_ADDRESS=server:5001
    volumes:
      - /proc:/proc:ro
      - /sys:/sys:ro
      - /:/rootfs:ro
    privileged: true
    cap_add:
      - SYS_ADMIN
    networks:
      - glimpse-network

networks:
  glimpse-network:
    driver: bridge 