// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/glimpse.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GlimpseService_Heartbeat_FullMethodName = "/glimpse.GlimpseService/Heartbeat"
)

// GlimpseServiceClient is the client API for GlimpseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GlimpseServiceClient interface {
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type glimpseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGlimpseServiceClient(cc grpc.ClientConnInterface) GlimpseServiceClient {
	return &glimpseServiceClient{cc}
}

func (c *glimpseServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, GlimpseService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GlimpseServiceServer is the server API for GlimpseService service.
// All implementations must embed UnimplementedGlimpseServiceServer
// for forward compatibility.
type GlimpseServiceServer interface {
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedGlimpseServiceServer()
}

// UnimplementedGlimpseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGlimpseServiceServer struct{}

func (UnimplementedGlimpseServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedGlimpseServiceServer) mustEmbedUnimplementedGlimpseServiceServer() {}
func (UnimplementedGlimpseServiceServer) testEmbeddedByValue()                        {}

// UnsafeGlimpseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GlimpseServiceServer will
// result in compilation errors.
type UnsafeGlimpseServiceServer interface {
	mustEmbedUnimplementedGlimpseServiceServer()
}

func RegisterGlimpseServiceServer(s grpc.ServiceRegistrar, srv GlimpseServiceServer) {
	// If the following call pancis, it indicates UnimplementedGlimpseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GlimpseService_ServiceDesc, srv)
}

func _GlimpseService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlimpseServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlimpseService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlimpseServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GlimpseService_ServiceDesc is the grpc.ServiceDesc for GlimpseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GlimpseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "glimpse.GlimpseService",
	HandlerType: (*GlimpseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _GlimpseService_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/glimpse.proto",
}
